version: '3.9'

  services:
    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: eais-backend-prod
      restart: unless-stopped
      ports:
        - "8000:8000"
      volumes:
        - ./lifts.xlsx:/app/lifts.xlsx
        - ./parfums.xlsx:/app/parfums.xlsx
        - ./bancomats.xlsx:/app/bancomats.xlsx
      environment:
        - ENVIRONMENT=production
        - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:8080}
      networks:
        - eais-network
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s

    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
        args:
          - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
      container_name: eais-frontend-prod
      restart: unless-stopped
      ports:
        - "8080:8080"
      depends_on:
        backend:
          condition: service_healthy
      networks:
        - eais-network
      healthcheck:
        test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80
        interval: 30s
        timeout: 3s
        retries: 3
   networks:
   eais-network:
     driver: bridge
