apiVersion: v1
 kind: Service
 metadata:
   name: backend-service
   namespace: eais-system
   labels:
     app: eais-backend
 spec:
    type: ClusterIP
   selector:
     app: eais-backend
   ports:
   - name: http
     protocol: TCP
     port: 8000
     targetPort: 8000
   sessionAffinity: ClientIP
