apiVersion: v1
 kind: ConfigMap
 metadata:
   name: eais-config
   namespace: eais-system
 data:
   ENVIRONMENT: "production"
   ALLOWED_ORIGINS: "http://eais.example.com,https://eais.example.com"
   VITE_API_URL: "http://backend-service:8000"
