apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: frontend-deployment
   namespace: eais-system
   labels:
     app: eais-frontend
 spec:
   replicas: 2
   selector:
     matchLabels:
       app: eais-frontend
   template:
     metadata:
       labels:
         app: eais-frontend
     spec:
       containers:
       - name: frontend
         image: your-registry/eais-frontend:latest
         imagePullPolicy: Always
         ports:
         - containerPort: 8080
           name: http
         resources:
           requests:
             memory: "128Mi"
             cpu: "100m"
           limits:
             memory: "256Mi"
             cpu: "200m"
         livenessProbe:
           httpGet:
             path: /
             port: 8080
           initialDelaySeconds: 30
           periodSeconds: 10
           timeoutSeconds: 5
           failureThreshold: 3
         readinessProbe:
           httpGet:
             path: /
             port: 8080
           initialDelaySeconds: 10
           periodSeconds: 5
           timeoutSeconds: 3
           failureThreshold: 3
